var terms = [
  "A Link to the Past",
  "Ache",
  "Acheman",
  "Acorn",
  "Acro Bandits",
  "Adult Wallet",
  "Adventure of Link",
  "Agahnim",
  "Agitha",
  "Amber",
  "Amiibo",
  "Ampilus",
  "Amy",
  "Ancient Screw",
  "Ancient Spring",
  "Anju",
  "Anti Fairy",
  "Anti Kirby",
  "Anubis",
  "Anubus",
  "Apple",
  "Aracha",
  "Argorok",
  "Arm Mimic",
  "Armogohma",
  "Armor",
  "Armored Train",
  "Armos",
  "Armos Knight",
  "Armos Titan",
  "Arrghus",
  "Arrow",
  "Arrow Moblin",
  "Arrows",
  "Aru Lowder",
  "Arwing",
  "Axe",
  "Baba Serpent",
  "Babusu",
  "Baby Dodongo",
  "Baby Gohma",
  "Bad Bat",
  "Bago Bago",
  "Baked Apple",
  "Bari",
  "Barinade",
  "Bazaar",
  "Beamos",
  "Bee",
  "Beedle",
  "Beetle",
  "Bellum Blob",
  "Beth",
  "Big Baba",
  "Big Blin",
  "Big Bomb Bag",
  "Big Deku Baba",
  "Big Octo",
  "Big Poe",
  "Big Quiver",
  "Big Skulltula",
  "Biggest Bomb Bag",
  "Biggest Quiver",
  "Biggoron",
  "Bigocto",
  "Bilocyte",
  "Bio Deku Baba",
  "Bio Electric Cube",
  "Bird Meat",
  "Biri",
  "Bit",
  "Black Boe",
  "Blade Trap",
  "Blastworm",
  "Blind the Theif",
  "Blizzeta",
  "Blooper",
  "Blue Anti Fairy",
  "Blue Bari",
  "Blue Bubble",
  "Blue ChuChu",
  "Blue Daira",
  "Blue Darknut",
  "Blue Deeler",
  "Blue Devalant",
  "Blue Fire",
  "Blue Fokka",
  "Blue Goriya",
  "Blue Guard",
  "Blue Iron Knuckle",
  "Blue Lanmola",
  "Blue Leever",
  "Blue Lizalfos",
  "Blue Lynel",
  "Blue Mail",
  "Blue Moa",
  "Blue Moblin",
  "Blue Mulldozer",
  "Blue Nightshade",
  "Blue Octorock",
  "Blue Octorok",
  "Blue Pesto",
  "Blue Potion",
  "Blue Rupee",
  "Blue Stalfos",
  "Blue Taurus",
  "Blue Tektite",
  "Blue Wizzrobe",
  "Bob omb",
  "Boe",
  "Boko Baba",
  "Boko Bow",
  "Boko Club",
  "Boko Shield",
  "Boko Spear",
  "Bokoblin",
  "Bokoblin Arm",
  "Bokoblin Fang",
  "Bokoblin Horn",
  "Bokoblin Liver",
  "Bolero Of Fire",
  "Bomb Arrow",
  "Bomb Bag",
  "Bomb Fish",
  "Bomb Flower",
  "Bombarossa",
  "Bombchu",
  "Bombchu Bowling",
  "Bomber",
  "Bombling",
  "Bombos",
  "Bombs",
  "Bomskit",
  "Bone Cucco",
  "Bone Putter",
  "Bongo Bongo",
  "Bonooru",
  "Boo Buddy",
  "Book of Mudora",
  "Boomerang",
  "Boon",
  "Boss Key",
  "Bot",
  "Boulder",
  "Bow",
  "Bow Moblin",
  "Bow Wow",
  "Bows and Arrows",
  "Breath of the Wild",
  "Broadsword",
  "Broken Goron Sword",
  "Bubble",
  "Bug",
  "Bug Catching Net",
  "Bulblin",
  "Bulblin Archer",
  "Bulblin Infantry",
  "Bulblin Rider",
  "Bulbul",
  "Bullbo",
  "Bunny Hood",
  "Business Scrub",
  "Butterfly",
  "Buzzblob",
  "Camo Goblin",
  "Candle",
  "Cane of Bryna",
  "Cane of Somaria",
  "Cannon Boat",
  "Chain Podobos",
  "Chamber of Sages",
  "Champion Shirt",
  "Chaser",
  "Chasupa",
  "Cheep Cheep",
  "Chilfos",
  "Chu",
  "Chu Worm",
  "ChuChu",
  "Chuchu Jelly",
  "Claim Check",
  "Claymore",
  "Cloud Piranha",
  "Club Moblin",
  "Cojiro",
  "Compass",
  "Courage",
  "Courser Bee Honey",
  "Crab",
  "Cranioc",
  "Crow",
  "Cryonis",
  "Cucco",
  "Cuccos",
  "Cukeman",
  "Cursed Bokoblin",
  "Cursed Spume",
  "Daira",
  "Dampe",
  "Dangerous",
  "Dark Blue Moa",
  "Dark ChuChu",
  "Dark Keese",
  "Dark Link",
  "Dark Lizalfos",
  "Dark Train",
  "Darknut",
  "Darunia",
  "Dead Hand",
  "Deadrock",
  "Death Armos",
  "Death Mountain",
  "Deeler",
  "Deep Python",
  "Deku Baba",
  "Deku Like",
  "Deku Scrub",
  "Deku Seeds",
  "Deku Shield",
  "Deku Stick",
  "Deku Tree",
  "Deku Tree Sprout",
  "Demise",
  "Desbreko",
  "Desert Colossus",
  "Desert Goddess",
  "Devalant",
  "Dexihand",
  "Dexivine",
  "Diababa",
  "Din",
  "Dinalfos",
  "Dinolfos",
  "Dodongo",
  "Dodongo Cavern",
  "Doomknocker",
  "Doomraddle",
  "Door Key",
  "Door Mimic",
  "Door of Time",
  "Dragonfly",
  "Dubious Food",
  "Dungeon",
  "Dungeon Key",
  "Dungeon Map",
  "Dynalfos",
  "Eeno",
  "Electro Spume",
  "Emerald",
  "Empty Bottle",
  "Endura Shroom",
  "Enduring Mushroom",
  "Energizing Elixir",
  "Energizing Mushroom",
  "Engagement Ring",
  "Epona",
  "Ergtorok",
  "Ether",
  "Eye of Truth",
  "Eye Plant",
  "Eye Slug",
  "Eyeball Frog",
  "Eyeball Monster",
  "Eyedrops",
  "Eyegore",
  "Failed Experiment",
  "Fairy",
  "Fairy Bow",
  "Fairy Ocarina",
  "Fairy Slingshot",
  "Farmer",
  "Farore",
  "Farores Wind",
  "Fi",
  "Fighter",
  "Fin Piranha",
  "Fire Arrow",
  "Fire Baba",
  "Fire Keese",
  "Fire Medallion",
  "Fire Moa",
  "Fire Pokey",
  "Fire Robe",
  "Fire Rod",
  "Fire Toadpoli",
  "Fire Wizzrobe",
  "Firewood",
  "Fish",
  "Flashing Bubble",
  "Flashing Rope",
  "Flint",
  "Flippers",
  "Floormaster",
  "Flute",
  "Flying Fish",
  "Flying Pot",
  "Flying Tile",
  "Fokka",
  "Fokkeru",
  "Food",
  "Force Gem Mimic",
  "Force Robe",
  "Forest Medallion",
  "Forest Stage",
  "Forest Temple",
  "Fountain",
  "Four Swords",
  "Freezard",
  "Freezor",
  "Froak",
  "Frostare Larva",
  "Furnix",
  "Fyrus",
  "Ganon",
  "Ganondorf",
  "Garo Robe",
  "Gel",
  "Geldarm",
  "Geldman",
  "Gerudo",
  "Gerudo Guard",
  "Gerudo Mask",
  "Gerudo Thief",
  "Gerudo Valley",
  "Gerune",
  "Ghini",
  "Ghirahim",
  "Ghoma",
  "Ghoma Egg",
  "Ghost Shop",
  "Ghoul Rat",
  "Giant Bee",
  "Giant Blade Trap",
  "Giant Bot",
  "Giant Ghini",
  "Giant Knife",
  "Giant Wallet",
  "Gibdo",
  "Gibo",
  "Girobokku",
  "GOALPOINT",
  "Gohdan",
  "Gohma",
  "Gohma Larva",
  "Goht",
  "Gold Gauntlets",
  "Gold Guard",
  "Gold Phantom",
  "Gold Skulltula",
  "Golden Goddesses",
  "Golden Octorok",
  "Golden Rope",
  "Golden Scale",
  "Golden Sword",
  "Golden Tektite",
  "Good Bee",
  "Goomba",
  "Goponga Flower",
  "Goriya",
  "Goron",
  "Goron Bracelet",
  "Goron City",
  "Goron Golem",
  "Goron Mask",
  "Goron Ruby",
  "Goron Tunic",
  "Gravedigging Tour",
  "Great Deku Tree",
  "Great Fairy",
  "Green Bubble",
  "Green ChuChu",
  "Green Eyegore",
  "Green Goriya",
  "Green Guard",
  "Green Kodondo",
  "Green Leever",
  "Green Mail",
  "Green Potion",
  "Green Rupee",
  "Green Zirro",
  "Groose",
  "Guardian",
  "Guay",
  "Guillotine",
  "Guru Guru",
  "Gyorg",
  "Hammer",
  "Happy Mask Salesman",
  "Happy Mask Shop",
  "Hardhat Beetle",
  "Hasty Meat",
  "Hasty Mushroom",
  "Haunted Wasteland",
  "Hearty Mushroom",
  "Hearty Radish",
  "Hearty Steamed Meat",
  "Hearty Truffle",
  "Hearty Wild Greens",
  "Heatoise",
  "Helmaroc King",
  "Helmasaur",
  "Helmasaurus",
  "Helmet ChuChu",
  "Hero of Time",
  "Hightail Lizard",
  "Hikkun",
  "Hinox",
  "Hiploop",
  "Hokbok",
  "Hookshot",
  "Horseback Archery",
  "Hot Footed Frog",
  "House of Twins",
  "Hover Boots",
  "Hrok",
  "Hue",
  "Huge Rupee",
  "Hylian Hornet",
  "Hylian Shield",
  "Hylian Shroom",
  "Hylian Trousers",
  "Hyrule",
  "Hyrule Bass",
  "Hyrule Castle",
  "Hyrule Guard",
  "Hyrule Herb",
  "Hyrule Market",
  "Ice Arrow",
  "Ice Arrows",
  "Ice Bubble",
  "Ice ChuChu",
  "Ice Keese",
  "Ice Keese Wing",
  "Ice Rod",
  "Ice Wizzrobe",
  "Imp Poe",
  "Impa",
  "Important Items",
  "Infinite Hand",
  "Ingo",
  "Ingo Ranch",
  "Iron Boots",
  "Iron Knuckle",
  "Iron Knuckles",
  "Iron Mask",
  "Iron Sledgehammer",
  "Jabu Jabu",
  "Jalhalla",
  "Kaepora Gaebora",
  "Kakariko Graveyard",
  "Kakariko Village",
  "Kalle Demos",
  "Karakoro",
  "Kargaroc",
  "Keaton",
  "Keaton Mask",
  "Keese",
  "Keese Eyeball",
  "Keese Swarm",
  "Keese Wing",
  "Key Master",
  "Kholdstare",
  "King Bubble",
  "King Daphnes Hyrule",
  "King Dodongo",
  "King of Evil",
  "King of Thieves",
  "King Zora",
  "Know It All Bros",
  "Kodondo",
  "Kokiri",
  "Kokiri Sword",
  "Koloktos",
  "Korok",
  "Korok Leaf",
  "Korok Seed",
  "Ku",
  "Kyameron",
  "Lake Hylia",
  "Lakeside Laboratory",
  "Lakitu",
  "Lamp",
  "Lanmola",
  "Lanmolas",
  "Leever",
  "Legend of Zelda",
  "Lens of Truth",
  "Letter",
  "Light Arrow",
  "Light Medallion",
  "Like Like",
  "LikeLike",
  "Linebeck",
  "Link",
  "Links Awakening",
  "Lizalfos",
  "Lobarrier",
  "Lon Lon Milk",
  "Lon Lon Ranch",
  "Longshot",
  "Lord Jabu Jabu",
  "Lost Woods",
  "Lowder",
  "Lullaby",
  "Lynel",
  "Mad Bomber",
  "Mad Scrub",
  "Magic",
  "Magic Bean",
  "Magic Cape",
  "Magic Jar",
  "Magic Meter",
  "Magic Mirror",
  "Magic Powder",
  "Magma Spume",
  "Magnesis",
  "Magnite",
  "Mago",
  "Magtail",
  "Majora",
  "Majoras Mask",
  "Malgyorg",
  "Malon",
  "Many sub varieties",
  "Mask Mimic",
  "Mask of Truth",
  "Master Sword",
  "Materials",
  "Mau",
  "Medicine Shop",
  "Medigoron",
  "Meg",
  "Megaton Hammer",
  "Megmat",
  "Membership Card",
  "Midna",
  "Mighty Darknut",
  "Mighty Zora Warrior",
  "Mini Baba",
  "Mini Freezard",
  "Mini Moldorm",
  "Miniblin",
  "Minuet of Forest",
  "Mirror Shield",
  "Moa",
  "Moblin",
  "Moblin Statue",
  "Moby",
  "Moink",
  "Moldarach",
  "Moldola",
  "Moldorm",
  "Moldworm",
  "Molgera",
  "Moon Pearl",
  "Morpha",
  "Morpheel",
  "Morth",
  "Moth",
  "Mothula",
  "Mountain Trail",
  "Mulldozer",
  "Mushroom",
  "Mushroom Skewer",
  "Myu",
  "Nabooru",
  "Navi",
  "Nayru",
  "Nayrus Love",
  "Nejiron",
  "Nocturn",
  "Nocturne of Shadow",
  "Nokken",
  "Nuranuru",
  "Ocarina of Time",
  "Octive",
  "Octoballoon",
  "Octomine",
  "Octorok",
  "Odd Mushroom",
  "Odd Potion",
  "Odolwa",
  "Old Man",
  "Old Shirt",
  "Opal",
  "Oracle of Ages",
  "Oracle of Seasons",
  "Orange Daira",
  "Orange Goriya",
  "Orange Iron Knuckle",
  "Orange Lizalfos",
  "Orange Moblin",
  "Pairodd",
  "Paraocto",
  "Parasitic Tentacle",
  "Peahat",
  "Peahat Larva",
  "Peahat Larvae",
  "Pedestal of Time",
  "Pegasus Boots",
  "Pegasus Shoes",
  "Pengator",
  "Pesto",
  "Phantom",
  "Phantom Eye",
  "Phantom Ganon",
  "Phantom Guide",
  "Phantom Hourglass",
  "Phantom Rider",
  "Piece of Heart",
  "Pierre",
  "Pikit",
  "Pincer",
  "Piranha Plant",
  "Pirogusu",
  "Pitchfork",
  "Pocket Cucco",
  "Pocket Egg",
  "Podobos",
  "Poe",
  "Poison Mite",
  "Pokey",
  "Pols Voice",
  "Popo",
  "Postman",
  "Pot Lid",
  "Potion Shop",
  "Power",
  "Power Glove",
  "Prelude of Light",
  "Prescription",
  "Prime Steak",
  "Princess Ruto",
  "Princess Zelda",
  "Pseudo Rupee",
  "Puffstool",
  "Puple Leever",
  "Puppet",
  "Puppet Ganon",
  "Purple Leever",
  "Purple Octorock",
  "Purple Rupee",
  "Purple Zirro",
  "Pygmy Skulltula",
  "Pyrup",
  "Quadro Baba",
  "Queen Gohma",
  "Quilted Shirt",
  "Rabbit Fang",
  "Rat",
  "Rauru",
  "Raven",
  "Real Bombchu",
  "Reapling",
  "Red Anti Fairy",
  "Red Bari",
  "Red Bubble",
  "Red ChuChu",
  "Red Daira",
  "Red Darknut",
  "Red Deeler",
  "Red Devalant",
  "Red Eyegore",
  "Red Fokka",
  "Red Goriya",
  "Red Guard",
  "Red Ice",
  "Red Iron Knuckle",
  "Red Kodondo",
  "Red Lanmola",
  "Red Leever",
  "Red Lizalfos",
  "Red Lynel",
  "Red Mail",
  "Red Moa",
  "Red Moblin",
  "Red Mulldozer",
  "Red Octorok",
  "Red Pesto",
  "Red Potion",
  "Red Rupee",
  "Red Sheild",
  "Red Stalfos",
  "Red Taurus",
  "Red Tektike",
  "Red Tektite",
  "Red Wizzrobe",
  "Redead",
  "Remlit",
  "Remote Bomb",
  "Requium of Spirit",
  "Restless Cricket",
  "Resurrection",
  "Richard",
  "River",
  "River Devil",
  "River Octorok",
  "River of Sand",
  "River Zora",
  "Rock ChuChu",
  "Rock Salt",
  "Rollobite",
  "Ropa",
  "Rope",
  "Royal Chamber",
  "Royal Composer Bros",
  "Royal Family",
  "Royal Family Tomb",
  "Ruby",
  "Rupee Like",
  "Rupee Wraith",
  "Rushroom",
  "Rusty Broadsword",
  "Sabooru",
  "Sacred Forest",
  "Sacred Realm",
  "Sages",
  "Sandworm",
  "Sapphire",
  "Saria",
  "Scaldera",
  "Scissors Beetle",
  "Sea Octorok",
  "Sea Urchin",
  "Seahat",
  "Seared Steak",
  "Sentrobe",
  "Serenade of Water",
  "Shabom",
  "Shadow Beast",
  "Shadow Insect",
  "Shadow Kargaroc",
  "Shadow Link",
  "Shadow Medallion",
  "Shadow Temple",
  "Sharp",
  "Sheikah",
  "Sheikah Slate",
  "Sheikah Towers",
  "Sheilds",
  "Shell Blade",
  "Shell Spinner",
  "Shield",
  "Shiro",
  "Shooting Gallery",
  "Shovel",
  "Shrine",
  "Shrine Ja Baij",
  "Shrine Kalm Yatakh",
  "Shrine Kalm Yuogh",
  "Shrine Ke Numut",
  "Shrine of Trials",
  "Shrine Oman Au",
  "Shrine Owa Daim",
  "Shrouded Stalfos",
  "Silent Shroom",
  "Silver Arrows",
  "Silver Gauntlets",
  "Silver Rupees",
  "Silver Scale",
  "Sir Frosty",
  "Sizzlewing",
  "Skull Kid",
  "Skull Mask",
  "Skullfish",
  "Skullrope",
  "Skulltula",
  "Skullwalltula",
  "Sky Tail",
  "Skyward Sword",
  "Slarok",
  "Slime",
  "Sluggula",
  "Small Key",
  "Snap Dragon",
  "Snapper",
  "Sneaky Steamed Fish",
  "Snurglar",
  "Snurgle",
  "Soldier",
  "Song of Storms",
  "Song of Time",
  "Spark",
  "Spear",
  "Spear Moblin",
  "Spicy Elixir",
  "Spicy Pepper",
  "Spicy Pepper Steak",
  "Spicy Peppers",
  "Spider of the Curse",
  "Spike",
  "Spiked Beetle",
  "Spiked Boko Bow",
  "Spiked Boko Shield",
  "Spin Attack",
  "Spinut",
  "Spiny Beetle",
  "Spiny ChuChu",
  "Spirit Medallion",
  "Spirit Orb",
  "Spirit Temple",
  "Spirit Tracks",
  "Spiritual Stones",
  "Spooky Mask",
  "Squiddy",
  "Stag Beetle",
  "Stalchild",
  "Staldra",
  "Stalfos",
  "Stalfos Knight",
  "Stalfos Warrior",
  "Stalhound",
  "Stalkin",
  "Stallord",
  "Staltroop",
  "Stamella Shroom",
  "Star",
  "Stasis",
  "Steak Skewer",
  "Steamed Mushrooms",
  "Stinger",
  "Stingers",
  "Stone of Agony",
  "Sunset Firefly",
  "Super Cuccos",
  "Swamola",
  "Swift Phantom",
  "Sword",
  "Syrup",
  "Tailparasan",
  "Tailpasaran",
  "Takkuri",
  "Talon",
  "Tank",
  "Taurus",
  "Technoblin",
  "Tektite",
  "Tempered Sword",
  "Temple of Time",
  "Tentalus",
  "Terrorpin",
  "The Imprisoned",
  "The Minish Cap",
  "Them",
  "Thief",
  "Thunder Keese",
  "Thwimp",
  "Thwomp",
  "Tile Worm",
  "Tingle",
  "Tinsuit",
  "Toado",
  "Toasty Shroom",
  "Topaz",
  "Torch",
  "Torch Phantom",
  "Torch Slug",
  "Training Ground",
  "Traveler",
  "Tree Branch",
  "Triforce",
  "Trinexx",
  "Turtle",
  "Twilight Assassin",
  "Twilight Princess",
  "Twilit Baba",
  "Twilit Bulblin",
  "Twilit Keese",
  "Twilit Vermin",
  "Twinmold",
  "Twinrova",
  "Vaati",
  "Vengas",
  "Venus Flytrap",
  "Vire",
  "Volvagia",
  "Vulture",
  "Wallmaster",
  "Walltula",
  "Warp Phantom",
  "Warship",
  "Watcher",
  "Water Medallion",
  "Water Spume",
  "Water Tektite",
  "Water Toadpoli",
  "Weapons",
  "Well Worn Pants",
  "White Boe",
  "White Bubble",
  "White Chuchu Jelly",
  "White Wolfos",
  "Wind Waker",
  "Winder",
  "Windmill",
  "Wisdom",
  "Wizzrobe",
  "Wolf Link",
  "Wolfos",
  "Woodcutter",
  "Wrecker Phantom",
  "Yellow ChuChu",
  "Yellow Wizzrobe",
  "Yook",
  "Yuga",
  "Zant",
  "Zant Mask",
  "Zelda",
  "Zirro",
  "Zol",
  "Zombie",
  "Zora",
  "Zora Mask",
  "Zora Tunic",
  "Zora Warrior",
  "Zoro"
];
